export const allGenres = [
  "acoustic",
  "adult contemporary",
  "afro house",
  "afrobeat",
  "afropop",
  "afro-latin",
  "alt pop",
  "alternative",
  "alternative r&b",
  "alternative rock",
  "ambient",
  "americana",
  "anime",
  "arabesque",
  "art pop",
  "avant-garde",
  "bachata",
  "balearic",
  "baroque",
  "bedroom pop",
  "bluegrass",
  "blues",
  "bolero",
  "boom bap",
  "bossa nova",
  "breakbeat",
  "britpop",
  "bubblegum pop",
  "celtic",
  "chamber pop",
  "chicago house",
  "chillhop",
  "chillout",
  "classical",
  "classic rock",
  "cloud rap",
  "club",
  "contemporary r&b",
  "conscious rap",
  "country",
  "country pop",
  "cumbia",
  "dance",
  "dance pop",
  "dancehall",
  "dark ambient",
  "deep house",
  "deep tech",
  "disco",
  "disco house",
  "downtempo",
  "dream pop",
  "drill",
  "drum and bass",
  "drumstep",
  "dub",
  "dub techno",
  "dubstep",
  "edm",
  "electro",
  "electronic",
  "electropop",
  "emo",
  "ethereal wave",
  "europop",
  "experimental",
  "folk",
  "folk rock",
  "french pop",
  "funk",
  "future bass",
  "future funk",
  "future house",
  "g-funk",
  "garage rock",
  "glam rock",
  "glitch",
  "gospel",
  "grime",
  "grunge",
  "hard bop",
  "hard rock",
  "hardcore",
  "hardstyle",
  "highlife",
  "hip hop",
  "honky tonk",
  "house",
  "hyperpop",
  "idm",
  "indie",
  "indie folk",
  "indie pop",
  "indie rock",
  "industrial",
  "instrumental",
  "j-pop",
  "j-rock",
  "jazz",
  "juke",
  "k-indie",
  "k-pop",
  "latin",
  "latin jazz",
  "latin pop",
  "latin trap",
  "liquid drum and bass",
  "lo-fi",
  "math rock",
  "melodic techno",
  "metal",
  "midwest emo",
  "minimal house",
  "minimal techno",
  "modern classical",
  "modern jazz",
  "motown",
  "neo-soul",
  "neoclassical",
  "new age",
  "new wave",
  "nu disco",
  "nu metal",
  "opera",
  "orchestral",
  "phonk",
  "pop",
  "pop punk",
  "post rock",
  "post-metal",
  "post-punk",
  "prog rock",
  "progressive house",
  "progressive metal",
  "progressive trance",
  "psychedelic",
  "psytrance",
  "punk",
  "r&b",
  "rap",
  "reggae",
  "reggae fusion",
  "reggaeton",
  "rock",
  "salsa",
  "shoegaze",
  "singer-songwriter",
  "ska",
  "ska punk",
  "soul",
  "soulful house",
  "soundtrack",
  "southern hip hop",
  "swing",
  "synth pop",
  "synthwave",
  "tech house",
  "techno",
  "trance",
  "trap",
  "trap soul",
  "trip hop",
  "tropical house",
  "turntablism",
  "uk garage",
  "vapor soul",
  "vaporwave",
  "vocal jazz",
  "west coast rap",
  "world",
  "worship",
  "zydeco",
];

export const normalizeGenre = (value: string) => value.trim().toLowerCase();

export const normalizeForSearch = (value: string) =>
  normalizeGenre(value).replace(/[^a-z0-9]+/g, "");
